### ISSUE TITLE
Android 14: lateinit property mDevicePolicyManager has not been initialized

### ISSUE THREAD

**Issue by moritz157** [itisnajim/device_policy_controller#11]
I call `DevicePolicyController.instance.lockApp()` to lock the app. This works fine on android 13 devices. However, as soon as I run the app on android 14, nothing happens (not even default pinning behaviour). Instead I get the following error:
```
PlatformException:PlatformException(error, lateinit property mDevicePolicyManager has not been initialized, null, c4.p: lateinit property mDevicePolicyManager has not been initialized at com.itisnajim.device_policy_controller.a.m(DevicePolicyControllerPlugin.kt:8) at com.itisnajim.device_policy_controller.a.q(DevicePolicyControllerPlugin.kt:13) at com.itisnajim.device_policy_controller.a.onMethodCall(DevicePolicyControllerPlugin.kt:326) at v3.k$a.a(MethodChannel.java:18) at k3.c.l(DartMessenger.java:19) at k3.c.m(DartMessenger.java:42) at k3.c.i(DartMessenger.java:1) at k3.b.run(R8$$SyntheticClass:13) at android.os.Handler.handleCallback(Handler.java:958) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:230) at android.os.Looper.loop(Looper.java:319) at android.app.ActivityThread.main(ActivityThread.java:8913) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) )
File "message_codecs.dart", line 648, in StandardMethodCodec.decodeEnvelope
File "platform_channel.dart", line 334, in MethodChannel._invokeMethod
?
File "device_policy_controller_platform_impl.dart", line 63, in DevicePolicyControllerPlatformImpl.lockApp
?
File "main.dart", line 217, in AppWidgetState.build.<fn>
```

Is there anything I can do to manually initialize everything inside the android plugin or is there some breaking change that breaks everything?

**EDIT:**
I tried what logcat could tell me and using `adb shell logcat | grep dpc::` I got the following over and over:
```
11-28 11:34:32.858  4593  4593 D dpc::   : onAttachedToEngine
11-28 11:34:32.878  4593  4593 D dpc::   : actions: android.app.action.DEVICE_ADMIN_ENABLED, android.intent.action.BOOT_COMPLETED, com.android.server.scannerservice.broadcast, com.android.server.scannerservice.shinow, android.intent.action.SCANRESULT, android.intent.ACTION_DECODE_DATA, android.intent.ACTION_DECODE_DATA, scan.rcv.message, com.ehsy.warehouse.action.BARCODE_DATA, com.honeywell.decode.intent.action.EDIT_DATA, android.intent.ACTION_BAR_SCAN, com.Dongting.WeScan.intent.action.ACTION_BAR_SCAN}
```

If I look at the code (`private fun initializeIfNeeded()`) the relevant section is this:
```kotlin
                log("actions: ${actions.joinToString(", ") }}")
                context.registerReceiver(appDeviceAdminReceiver, intentFilter)
                adminComponentName = appDeviceAdminReceiver.getWho(context)
                log("registerReceiver packageName: " + adminComponentName.packageName + ", className: " + adminComponentName.className)
```
which looks to me as if there is a logged line missing, so the could probably fails somewhere between `log("actions: ...` and `log("registerReceiver...`. That would make sense as the property `mDevicePolicyManager` is initialized right after the missing log line.

This might be related to this breaking change: https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported

**Comment by moritz157** [comment]
Alright, it seems I have got a fix. Following the mentioned breaking change, I changed `context.registerReceiver(appDeviceAdminReceiver, intentFilter)` to `context.registerReceiver(appDeviceAdminReceiver, intentFilter, 2)`. I supplied 2 as a flag, since `context.RECEIVER_EXPORTED` seems to not be available, but 2 is the underlying value (https://developer.android.com/reference/android/content/Context#RECEIVER_EXPORTED).

I honestly don't really know what I am doing here, but I someone else does, this is perhaps a very needed fix to include here.
